### ISSUE TITLE
Feature Idea: Apple TV & Video Directory

### ISSUE THREAD

**Issue by jstart** [BalestraPatrick/RealmVideo#2]
Any thoughts of supporting Apple TV or scraping Realm to provide a list of videos?

**Comment by BalestraPatrick** [comment]
Nice idea! I'm not sure if the hack I am using to present the slides over the video player works on Apple TV but it can be taken into consideration for sure.
I have tried looking into the Realm website and I haven't found a single page that contains the latest videos yet. I will keep working on it😄

**Comment by BalestraPatrick** [comment]
It's actually possible to scrape all the videos by reading the `data-tags` attribute of each `post` divs.
<img width="1680" alt="screen shot 2016-05-06 at 9 34 28 pm" src="https://cloud.githubusercontent.com/assets/3658887/15084245/901913b6-13d2-11e6-814a-073d54cea4cb.png">

**Comment by BalestraPatrick** [comment]
@jstart Video directory just implemented 👍

**Comment by jstart** [comment]
👍  nice!
