### ISSUE TITLE
Error in Ji

### ISSUE THREAD

**Issue by Viniciuscarvalho** [BalestraPatrick/RealmVideo#3]
When compile in first time is in need of the `Ji` module.

**Comment by BalestraPatrick** [comment]
I've updated the README with instructions on how to install the `Ji` library with CocoaPods. Please run `pod install` and open the xcworkspace project. Let me know if that fixes your issue.

**Comment by Viniciuscarvalho** [comment]
That's fine when run `pod install` and works!
Thanks. 👍
