### ISSUE TITLE
Can't pod install with Cocoapods 1.0.0

### ISSUE THREAD

**Issue by mbeaty** [BalestraPatrick/RealmVideo#6]
I'm not a Cocoapods expert, but I assume the pod spec for this library needs to be updated to work with Cocoapods 1.0. In any event, I only got 'pod install' to work by using Cocoapods 0.39.

**Comment by BalestraPatrick** [comment]
Hey! I installed CocoaPods 1.0.0 and I don't have any issue running `pod install`. Can you please describe your output?

**Comment by mbeaty** [comment]
Here you go:

➜  RealmVideo git:(master) ✗ pod --version
1.0.0
➜  RealmVideo git:(master) ✗ pod install
Re-creating CocoaPods due to major version update.
Analyzing dependencies
[!] Unable to satisfy the following requirements:
- `Ji (~> 1.2.0)` required by `Podfile`
- `Ji (= 1.2.0)` required by `Podfile.lock`

None of your spec sources contain a spec satisfying the dependencies: `Ji (~> 1.2.0), Ji (= 1.2.0)`.

You have either:
- out-of-date source repos which you can update with `pod repo update`.
- mistyped the name or version.
- not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by BalestraPatrick** [comment]
Have you tried removing the `Podfile.lock` file and then doing `pod install`?

**Comment by BalestraPatrick** [comment]
You should try with 801a56e which I just pushed. I notice that by doing `pod install` on my machine it bumped the CocoaPods version to 1.0.0 and a bunch of other files. Let me know if that fixes your issue.

**Comment by BalestraPatrick** [comment]
@mbeaty Were you able to fix the issue?
