### ISSUE TITLE
Back out to list

### ISSUE THREAD

**Issue by fbara** [BalestraPatrick/RealmVideo#7]
I installed to both my iPad and iPhone.  I can start the video and see the slides without a problem.  How do I go back to the list of Realm videos?  In order to go back to the list I have to force-quit the app and open it back up again.  I think I'm missing how to go back.

**Comment by BalestraPatrick** [comment]
There is no way of doing that at this moment. Do you have any advice on how we could go about implementing this feature? The view controller displays the video full screen so there is no space to put a button.

**Comment by fbara** [comment]
Maybe a two-finger slide gesture could take you back?  If I get some time from work I can try it.

**Comment by BalestraPatrick** [comment]
@fbara You're welcome to work on it 😄
